/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cell-frequencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Cell Frequencies */
        get: operations["read_cell_frequencies_api_cell_frequencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/response-frequency-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Response Frequency Analysis */
        get: operations["read_response_frequency_analysis_api_response_frequency_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Samples */
        get: operations["read_samples_api_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/field-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Samples Field Values */
        get: operations["read_samples_field_values_api_samples_field_values_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BoxplotStats */
        BoxplotStats: {
            /** Minimum */
            minimum: number;
            /** Q1 */
            q1: number;
            /** Median */
            median: number;
            /** Q3 */
            q3: number;
            /** Maximum */
            maximum: number;
        };
        /** CellFrequencyRow */
        CellFrequencyRow: {
            /** Sample */
            sample: string;
            /** Population */
            population: string;
            /** Count */
            count: number;
            /** Total Count */
            total_count: number;
            /** Percentage */
            percentage: number;
        };
        /** GroupCount */
        GroupCount: {
            /** Group */
            group: string;
            /** Count */
            count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PopulationBoxplot */
        PopulationBoxplot: {
            /** Population */
            population: string;
            responder: components["schemas"]["BoxplotStats"];
            non_responder: components["schemas"]["BoxplotStats"];
            /** Statistic */
            statistic: number;
            /** Significant */
            significant: boolean;
        };
        /** ResponseFrequencyAnalysis */
        ResponseFrequencyAnalysis: {
            /** Methodology */
            methodology: string;
            /** Boxplots */
            boxplots: components["schemas"]["PopulationBoxplot"][];
        };
        /** SampleRecord */
        SampleRecord: {
            /** Project Source Id */
            project_source_id: string;
            /** Condition */
            condition: string | null;
            /** Treatment */
            treatment: string | null;
            /** Subject Source Id */
            subject_source_id: string;
            /** Age */
            age: number;
            /** Sex */
            sex: string;
            /** Response */
            response: string | null;
            /** Sample Type */
            sample_type: string;
            /** Time From Treatment */
            time_from_treatment: number;
            /** B Cell */
            b_cell: number;
            /** Cd8 T Cell */
            cd8_t_cell: number;
            /** Cd4 T Cell */
            cd4_t_cell: number;
            /** Nk Cell */
            nk_cell: number;
            /** Monocyte */
            monocyte: number;
        };
        /** SamplesResult */
        SamplesResult: {
            /** Samples */
            samples: components["schemas"]["SampleRecord"][];
            /** Counts */
            counts: components["schemas"]["GroupCount"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_cell_frequencies_api_cell_frequencies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellFrequencyRow"][];
                };
            };
        };
    };
    read_response_frequency_analysis_api_response_frequency_analysis_get: {
        parameters: {
            query: {
                condition: string;
                treatment: string;
                sample_type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseFrequencyAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_samples_api_samples_get: {
        parameters: {
            query?: {
                grouping?: ("project" | "subject") | null;
                condition?: string | null;
                treatment?: string | null;
                sample_type?: string | null;
                time_from_treatment?: number | null;
                group_count_field?: ("sex" | "response") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamplesResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_samples_field_values_api_samples_field_values_get: {
        parameters: {
            query: {
                field: "condition" | "treatment" | "sample_type" | "time_from_treatment";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
